import Head from "next/head";
import React, { useEffect } from "react";
import Image from "next/image";
import { Inter, Junge } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { auth } from "../serve/firebase";
import { useAuthState } from "react-firebase-hooks/auth";

import Jumbotron from "@/components/Jumbotron";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [user, loading, error] = useAuthState(auth);

  return (
    <>
      <Head>
        <title>EmpowrHer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700;800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        {user ? <Jumbotron user={user} /> : <Jumbotron user={false} />}
      </main>
    </>
  );
}
