import React from 'react'
import Head from "next/head";

function Heading() {
    return (
        <Head>
            <title>EmpowrHer</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />

            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
            <link
                href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700;800&display=swap"
                rel="stylesheet"
            />
        </Head>
    )
}

export default Heading